import type { Metadata } from 'next';
import ThemeProvider from '../context/ThemeProvider';
import StoreProvider from './StoreProvider';
import Header from '../components/Header';
import { Suspense } from 'react';
import Loading from './loading';
import './globals.css';

export const metadata: Metadata = {
  title: 'Star Wars Api',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <ThemeProvider>
            <Header />
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
