import { Links, Meta, Outlet, Scripts, ScrollRestoration } from '@remix-run/react';
import './global.css';
import { LinksFunction, MetaFunction } from '@remix-run/node';
import ThemeProvider from './context/ThemeProvider';
import { Provider } from 'react-redux';
import { store } from './redux/store';
import Header from './components/Header';

export const meta: MetaFunction = () => [
  { title: 'Star Wars Api' },
  { name: 'description', content: 'Generated by remix app' },
];
export const links: LinksFunction = () => [{ rel: 'icon', type: 'image/png', href: '/favicon.ico' }];

export function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Meta />
        <Links />
      </head>
      <body>
        {children}
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}

export default function App() {
  return (
    <Provider store={store}>
      <ThemeProvider>
        <Header />
        <Outlet />
      </ThemeProvider>
    </Provider>
  );
}
